on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    # Step 1: Checkout the code
    - uses: actions/checkout@v3

    # Step 2: Setup .NET 8 SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x

    # Step 3: Install MAUI workload (for MAUI-based projects)
    - name: Install MAUI workload
      run: dotnet workload install maui

    # Step 4: Install Node.js (required for Appium)
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    # Step 5: Install Appium (via npm)
    - name: Install Appium
      run: npm install -g appium

    # Step 6: Install WinAppDriver for Windows UI testing
    - name: Install WinAppDriver
      run: |
        Invoke-WebRequest -Uri https://github.com/microsoft/WinAppDriver/releases/download/v1.2.1/WindowsApplicationDriver_1.2.1.msi -OutFile WinAppDriver.msi
        Start-Process msiexec.exe -Wait -ArgumentList '/I WinAppDriver.msi /quiet'

    # Step 7: Start WinAppDriver
  

    # Step 9: Build the project
    - name: Build
      run: dotnet build Yaml/Yaml.csproj -c Release -f:net8.0-windows10.0.19041.0

    # Step 10: Run Appium-based tests
    - name: Run Tests
      run: dotnet test UITests.Windows/UITests.Windows.csproj --logger "trx;LogFileName=test_results.trx" --results-directory ./TestResults

    # Step 11: Upload test results as artifacts for review
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: ./TestResults/test_results.trx
