on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x

    - name: Install MAUI workload
      run: dotnet workload install maui

    # Install WinAppDriver required for running Windows UI tests
    - name: Install WinAppDriver
      run: |
        Invoke-WebRequest -Uri https://github.com/microsoft/WinAppDriver/releases/tag/v1.2.1/WindowsApplicationDriver_1.2.1.msi -OutFile WinAppDriver.msi
        Start-Process msiexec.exe -Wait -ArgumentList '/I WinAppDriver.msi /quiet'

    # Start WinAppDriver
    - name: Start WinAppDriver
      run: Start-Process WinAppDriver.exe

    # Build the project
    - name: Build
      run: dotnet build Yaml/Yaml.csproj -c Release -f:net8.0-windows10.0.19041.0

    # Run Appium-based tests
    - name: Run Tests
      run: dotnet test UITests.Windows/UITests.Windows.csproj --logger "trx;LogFileName=test_results.trx" --results-directory ./TestResults

    # Upload test results as artifacts for review
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: ./TestResults/test_results.trx
